{{- if and .Values.cluster.create .Values.cluster.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.cluster.name }}-kingbase
  namespace: {{ .Values.cluster.namespace }}
  labels:
    {{- include "kingbase.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.cluster.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "kingbase.clusterSelectorLabels" . | nindent 6 }}
{{- end }}
